@extends('admin.main')
@php
use App\Helpers\Form as FormTemplate;
use App\Helpers\Template;
use App\Models\ProductCategory as mainModel;

$formInputAttr = config('zvn.template.form_input');
$formLabelAttr = config('zvn.template.form_label');
$keep_parent = [''=>'-- Option --' , 0 => "No" , 1 => 'Yes']
@endphp

@section('content')
@include ('admin.templates.page_header', ['pageIndex' => false])
@include ('admin.templates.error')

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            @include('admin.templates.x_title', ['title' => 'Form'])
            <div class="x_content">
                {{ Form::open([
                        'method'         => 'GET', 
                        'url'            => route("$controllerName/autoGeneratedSave"),
                        'accept-charset' => 'UTF-8',
                        'enctype'        => 'multipart/form-data',
                        'class'          => 'form-horizontal form-label-left',
                        'id'             => 'main-form' ])  }}
                <div class="form-group">
                    {{ Form::label('category_id','Main Category Name',['class'=>'control-label col-md-3 col-sm-3 col-xs-12']) }}
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        {{ Form::text('name','',['class'=>'form-control col-md-6 col-xs-12'])}}
                    </div>
                </div>

                <div class="form-group">
                    {{ Form::label('parent_id','ID',['class'=>'control-label col-md-3 col-sm-3 col-xs-12']) }}
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        {{ Form::number('parent_id','',['class'=>'form-control col-md-6 col-xs-12'])}}
                    </div>
                </div>

                <div class="form-group">
                    {{ Form::label('keep_parent','Do you want to keep the parent is a root?',['class'=>'control-label col-md-3 col-sm-3 col-xs-12']) }}
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        {{ Form::select('keep_parent',$keep_parent,'' ,['class'=>'form-control col-md-6 col-xs-12'])}}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        {{ Form::submit('Save',['class'=>'btn btn-success'])}}
                    </div>
                </div>

                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection